 define(['jquery','block_accessibility/atbar','block_accessibility/textsize',
     'block_accessibility/color','core/config','core/str','block_accessibility/util'],
     function($,atbar,textsize,changecolor,config,string,util){
    var DEFAULT_FONTSIZE = 100;
    //var MAX_FONTSIZE = 197;
    //var MIN_FONTSIZE =77;
    var DEFAULT_PX_FONTSIZE= 13;
    var MAX_PX_FONTSIZE= 26;
    var MIN_PX_FONTSIZE= 10+1; // +1 because of unknown error...YUI for 77% returns style of 11px
    var MAIN_SELECTOR  = '#page'; // userstyles.php applies CSS font-size to this element
    //stylesheet: '',
    var sheetnode =  '';

    var defaultsize =  null;
    var watch =  null;
    var debug = false;
    var transactionsCount = 0; // AJAX transactions


    return {
        /**
         * Stylesheet is generated by userstyles.php based on user settings (e.g. font size)
         * After settings are changed, the script should download and include updated stylesheet
         *
         */
        MAIN_SELECTOR: '#page',
        init: function( autoload_atbar, instance_id) {
            // keep in mind that dynamic AJAX mode cannot work properly with
            // IE <= 8 (for now), so this script will not even be loaded in block_accessibillity.php
            // TO-DO: determine if block is visible (for example in chat session is not)
            console.log("Im initialised!");
            var self = this;
            self.instance_id = instance_id;
            this.setInstanceID(instance_id);
            console.log(instance_id);
            util.sheetnode = $('link[href="'+config.wwwroot+
                '/blocks/accessibility/userstyles.php?instance_id='+instance_id+'"]');
            //TODO Jquery
            //this.sheetnode = $('link[href="'+config.wwwroot+
              //  '/blocks/accessibility/userstyles.php?instance_id='+this.getInstanceID()+'"]');
            //this.stylesheet = Y.StyleSheet(this.sheetnode);


            // Set default font size
            //this.log('Initial size: '+Y.one('body').getStyle('fontSize'));
            defaultsize = DEFAULT_FONTSIZE;

            // Attach the click handler


            $('#block_accessibility_textresize a').on('click', function() {
                console.log("Text resize button was clicked");
                if (!$(this).hasClass('disabled')) {
                    // If it is, and the button's not disabled, pass it's id to the changesize function
                    if(textsize.changesize($(this),instance_id)){
                        console.log("changesize");
                    }
                }
            });

            $('#block_accessibility_changecolour a').on('click', function() {
                if (!$(this).hasClass('disabled')) {
                    // If it is, and the button's not disabled, pass it's id to the changecolour function
                    if(changecolor.changecolor($(this),instance_id)){
                        console.log("true");
                    }
                }
            });
            // Remove href attributes from anchors
            $('#accessibility_controls a').each(function(index){
               $(this).removeAttr('href');
            });

            //TODO Jquery
            // ATBar might be disabled in block's config
            if($('#atbar_auto') !== null){
                // checkbox for setting 'always' chackbox
                $('#atbar_auto').on('click', function() {
                    if ($(this).is(':checked')) {
                        atbar.atbar_autoload('on');
                    } else {
                        atbar.atbar_autoload('off');
                    }
                });
                //TODO Jquery
                // Create Bookmarklet-style link using code from ATbar site
                // http://access.ecs.soton.ac.uk/StudyBar/versions
                $('#block_accessibility_launchtoolbar').on('click', function() {
                    atbar.load_atbar();

                    // Do we really need it?
                    // Hide block buttons until ATbar is closed
                    //$('#block_accessibility_textresize').css('display','none');
                    //$('#block_accessibility_changecolour').css('display','none');
                    //watch_atbar_for_close();
                });

                if (autoload_atbar) {
                    atbar.load_atbar();

                    //If clean theme is used then shift the ATbar down by 40px
                    if(config.theme === 'clean'){
                        $('#sbar').css('top','40px !important');
                    }
                    // Hide block buttons until ATbar is closed
                   // $('#block_accessibility_textresize').css('display','none');
                    //$('#block_accessibility_changecolour').css('display','none');
                    // Wait 1 second to give the bar a chance to load
                    //setTimeout("watch_atbar_for_close();", 1000);
                }
            }
        },
        setInstanceID: function(id){
           instance_id = id;
        }
    };
});
