 define(['jquery','block_accessibility/atbar','block_accessibility/textsize',
     'block_accessibility/color','core/config','core/str'],
     function($,atbar,textsize,changecolor,config,string){
    var DEFAULT_FONTSIZE = 100;
    //var MAX_FONTSIZE = 197;
    //var MIN_FONTSIZE =77;
    var DAFAULT_PX_FONTSIZE= 13;
    var MAX_PX_FONTSIZE= 26;
    var MIN_PX_FONTSIZE= 10+1; // +1 because of unknown error...YUI for 77% returns style of 11px
    var MAIN_SELECTOR  = '#page'; // userstyles.php applies CSS font-size to this element
    //stylesheet: '',
    var sheetnode =  '';

    var defaultsize =  null;
    var watch =  null;
    var debug = false;
    var transactionsCount = 0; // AJAX transactions
         /**
          * Stylesheet is generated by userstyles.php based on user settings (e.g. font size)
          * After settings are changed, the script should download and include updated stylesheet
          *
          */
         function reload_stylesheet(id){
             console.log("reloading stylesheet...");
             var sheetnode = $('link[href="'+config.wwwroot+
                 '/blocks/accessibility/userstyles.php?instance_id='+id+'"]');
             console.log(sheetnode);
             var cache_prevention_salt = new Date().getTime();
             var oldStylesheet = sheetnode;
             var newStylesheet = null;
             var cssURL = config.wwwroot+
                 '/blocks/accessibility/userstyles.php?instance_id='+
                 this.instance_id+
                 '&v='+cache_prevention_salt;
             if (document.createStyleSheet) // only for IE < 11 and IE > 8
             {
                 /*
                  here we use href attribute change which makes some delay while reloading stylesheet

                  1. one another idea would be to load stylesheet using this.Y.io(.. and create <style> element
                  var styleSheet = document.createElement('STYLE');
                  document.documentElement.firstChild.appendChild(styleSheet);

                  2. initial idea was the same as for non-IE browsers but somehow doesn't work:
                  oldStylesheet.remove(true);
                  newStylesheet = document.createStyleSheet(cssURL);
                  // also keep in mind that createStyleSheet can create up to 31 stylesheets
                  // http://msdn.microsoft.com/en-us/library/ie/ms531194(v=vs.85).aspx
                  */
                 oldStylesheet.attr('href',cssURL);
             }
             else{
                 // IE 11 and non-IE browsers:
                 // creating new stylesheet and deleting old one makes more smooth transition
                 // Why wouldn't we just set the href attribute insted of creating another stylesheet node? Because before the new stylesheet is loaded and while old one is deleted, the page will lose all the styles and all the elements get unstyled for a some time (poor user experience)
                 newStylesheet = oldStylesheet.clone(true);
                 newStylesheet.attr('href', cssURL);
                 $('head').append(newStylesheet);
                 // remove old stylesheet
                 newStylesheet.load(function(){
                     oldStylesheet.remove();
                 });
             }
         }

    return {
        init: function( autoload_atbar, instance_id) {
            // keep in mind that dynamic AJAX mode cannot work properly with
            // IE <= 8 (for now), so this script will not even be loaded in block_accessibillity.php

            // TO-DO: determine if block is visible (for example in chat session is not)
            console.log("Im initialised!");
            var self = this;
            self.instance_id = instance_id;
            this.setInstanceID(instance_id);
            console.log(instance_id);

            //TODO Jquery
            //this.sheetnode = $('link[href="'+config.wwwroot+
              //  '/blocks/accessibility/userstyles.php?instance_id='+this.getInstanceID()+'"]');
            //this.stylesheet = Y.StyleSheet(this.sheetnode);


            // Set default font size
            //this.log('Initial size: '+Y.one('body').getStyle('fontSize'));
            defaultsize = DEFAULT_FONTSIZE;

            // Attach the click handler


            $('#block_accessibility_textresize a').on('click', function() {
                if (!$(this).target.hasClass('disabled')) {
                    // If it is, and the button's not disabled, pass it's id to the changesize function
                    if(textsize.changesize($(this))){
                        reload_stylesheet();
                    }
                }
            });

            $('#block_accessibility_changecolour a').on('click', function() {
                if (!$(this).hasClass('disabled')) {
                    // If it is, and the button's not disabled, pass it's id to the changecolour function
                    if(changecolor.changecolor($(this))){
                        console.log("true");
                        reload_stylesheet(instance_id);
                    }
                }
            });

            // Remove href attributes from anchors
            $('#accessibility_controls a').each(function(index){
               $(this).removeAttr('href');
            });

            //TODO Jquery
            // ATBar might be disabled in block's config
            if($('#atbar_auto') !== null){
                // checkbox for setting 'always' chackbox
                $('#atbar_auto').on('click', function(e) {
                    if ($(this).checked) {
                        atbar.atbar_autoload('on');
                    } else {
                        atbar.atbar_autoload('off');
                    }
                });
                //TODO Jquery
                // Create Bookmarklet-style link using code from ATbar site
                // http://access.ecs.soton.ac.uk/StudyBar/versions
                $('#block_accessibility_launchtoolbar').on('click', function() {
                    console.log("I was clicked!");
                    atbar.load_atbar();

                    // Do we really need it?
                    // Hide block buttons until ATbar is closed
                    //$('#block_accessibility_textresize').css('display','none');
                    //$('#block_accessibility_changecolour').css('display','none');
                    //watch_atbar_for_close();
                });

                if (autoload_atbar) {
                    atbar.load_atbar();

                    //If clean theme is used then shift the atbar down by 40px
                    if(config.theme === 'clean'){
                        $('#sbar').css('top','40px !important');
                    }
                    // Hide block buttons until ATbar is closed
                   // $('#block_accessibility_textresize').css('display','none');
                    //$('#block_accessibility_changecolour').css('display','none');
                    // Wait 1 second to give the bar a chance to load
                    //setTimeout("watch_atbar_for_close();", 1000);
                }
            }
        },
        setInstanceID: function(id){
           instance_id = id;
        },
        getInstanceID:function(){
            return instance_id;
        }

    };
});
