define(['jquery','core/config'],function($,config){
    var SAVE_LOCATION = config.wwwroot+'/blocks/accessibility/database.php';
    return{
        sendRequest : function(location,data){
            $.ajax({
                url: location,
                method:'GET',
                data:data,
                beforeSend: this.show_loading,
                complete: this.hide_loading
            });
        },
        /**
         * Stylesheet is generated by userstyles.php based on user settings (e.g. font size)
         * After settings are changed, the script should download and include updated stylesheet
         *
         */

        reload_stylesheet:function(){
            var cache_prevention_salt = new Date().getTime();
        }
    };

});
